.Dd $Mdocdate: March 11 2022 $
.Dt WEBSTORM 1
.Os
.Sh NAME
.Nm webstorm
.Nd launch WebStorm JavaScript Integrated Development Environment
.Sh SYNOPSIS
.Nm
.Op jvm-args
.Sh DESCRIPTION
.Nm
starts up the JetBrains WebStorm JavaScript Integrated
Development Environment.
.Sh SEE ALSO
The web site
.Lk https://www.jetbrains.com/webstorm/ .
