#!/bin/sh
# OpenBSD-specific startup script for WebStorm IDE

WEBSTORM_HOME=${TRUEPREFIX}/webstorm

#-----------------------------------------------------------------------------
# Determine configuration settings
#-----------------------------------------------------------------------------

export JAVA_BIN=$(javaPathHelper -c webstorm)
export JAVA_HOME=$(javaPathHelper -h webstorm)

if [ ! -x "${JAVA_BIN}" ]; then
	echo "Error: JAVA_HOME may not be defined correctly: ${JAVA_HOME}"
	echo "       Unable to find Java binary ${JAVA_BIN}"
	exit 1
fi

# Check if 'webstorm' executable can be found
if [ ! -x "${WEBSTORM_HOME}/bin/webstorm.sh" ]; then
	echo "Error: WEBSTORM_HOME may not be defined correctly: ${WEBSTORM_HOME}"
	echo -n "       Unable to find launcher binary: "
	echo "${WEBSTORM_HOME}/bin/webstorm.sh"
	exit 1
fi

PATH=${JAVA_HOME}/bin:$PATH exec "${WEBSTORM_HOME}/bin/webstorm.sh" -e $@
